blank_issues_enabled: true
contact_links:
  - name: "ğŸ’¬ Join Discord"
    about: Chat with us about general questions, issues or suggestions.
    url: https://discord.gg/wXy6m2X8wY

  - name: "ğŸ“ Submit Feedback"
    about: Send general feedback through the website.
    url: https://cssnr.github.io/feedback
