blank_issues_enabled: true
contact_links:
  - name: "ğŸ’¬ Join Discord"
    about: Chat with us about Issues, Features, Questions and More.
    url: https://discord.gg/wXy6m2X8wY

  - name: "ğŸ“ Submit Feedback"
    about: Send General Feedback.
    url: https://cssnr.github.io/feedback
